apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: pathnex-grafana
spec:
  type: {{ .Values.service.type }}
  selector:
    app: pathnex-grafana
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}